### ISSUE TITLE
Question about the animals

### ISSUE THREAD

**Issue by vm-wylbur** [CDukich/study#3]
What about the pets? Have they all been eaten? Perhaps you should check.

**Comment by vm-wylbur** [comment]
No action yet?! I'm waiting! Close the issue! make things happen! 
![pb-sn-papers-20150926](https://cloud.githubusercontent.com/assets/1772592/12028281/897db156-ad89-11e5-9a5e-6d0eb50182cc.jpg)

**Comment by vm-wylbur** [comment]
It's not closed until you make a comment saying why it's closed: 
- why was it closed?
- maybe it should never have been opened?
- what else should we think about?

**Comment by CDukich** [comment]
This is now closed
